### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by ashwinvish** [aherbert/GDSC#1]
I seem to have an error running FindFoci from Fiji. Any idea what is wrong?
(Fiji Is Just) ImageJ 2.0.0-rc-61/1.51n; Java 1.8.0_66 [64-bit]; Mac OS X 10.11.6; 60MB of 5288MB (1%)
 
<java.lang.NoClassDefFoundError: ij/gui/ExtendedGenericDialog
	at gdsc.foci.FindFoci.run(FindFoci.java:695)
	at ij.IJ.runUserPlugIn(IJ.java:217)
	at ij.IJ.runPlugIn(IJ.java:181)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at ij.IJ.run(IJ.java:297)
	at ij.macro.Functions.doRun(Functions.java:601)
	at ij.macro.Functions.doFunction(Functions.java:96)
	at ij.macro.Interpreter.doStatement(Interpreter.java:230)
	at ij.macro.Interpreter.doStatements(Interpreter.java:218)
	at ij.macro.Interpreter.run(Interpreter.java:115)
	at ij.macro.Interpreter.run(Interpreter.java:85)
	at ij.macro.Interpreter.run(Interpreter.java:96)
	at ij.plugin.Macro_Runner.runMacro(Macro_Runner.java:155)
	at ij.plugin.Macro_Runner.runMacroFile(Macro_Runner.java:139)
	at ij.plugin.Macro_Runner.run(Macro_Runner.java:35)
	at ij.IJ.runPlugIn(IJ.java:187)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: ij.gui.ExtendedGenericDialog
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)>

**Comment by aherbert** [comment]
The GDSC and GDSC-SMLM update sites both use the same gdsc-core jar library. However the GDSC-SMLM site has an older version. This site has not been updated since 2016-09. When you check both update sites in Fiji it seems that the older version wins over the newer version.

Basically you can only run the GDSC plugins or the GDSC-SMLM plugins, but not both together. This will be fixed in the future but for now you will have to remove the GDSC-SMLM update site.

The GDSC-SMLM plugins are used for super-resolution microscopy analysis. They are not required for anything in the GDSC plugins. The two plugin sets contain code that work together within the set, but each set of plugins is mutually exclusive (i.e. they do not work with each other).

If you want to use the GDSC plugins and also the GDSC-SMLM plugins then the workaround is to have two instances of ImageJ, one for each set of plugins.

**Comment by aherbert** [comment]
I'm leaving this open so it catches the attention of anyone who is watching. I will close it when the two sets of plugins can work together. 

The current version of the GDSC-SMLM plugins are not documented so haven't been released. If you want to use the GDSC SMLM plugins then I can provide them to you. They will be able to run in parallel with the GDSC plugins.
